# Generated by Django 4.1.7 on 2023-03-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('matricula', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('zonaatencion', models.CharField(max_length=40)),
                ('modalidadatencion', models.CharField(max_length=40)),
                ('orientacion', models.CharField(max_length=40)),
                ('especialidad', models.CharField(max_length=40)),
                ('tipotratamiento', models.CharField(max_length=40)),
            ],
        ),
    ]
